Repository compucorp/civihr-employee-portal, pull requests merged in 2018-08, with the labels that each got.

#531 PCHR-4004: Removing HR Vacancies From SSP
  civihr_employee_portal/civihr_employee_portal.install
  civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.features.menu_links.inc
  civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.info
  civihr_employee_portal/views/civihr_employee_portal.views.inc
  civihr_employee_portal/views/views_export/views_hr_vacancies.inc
Labels: ready to test

#533 PCHR-4073: Fix SSP Filter on Staff Directory
  civihr_employee_portal/src/View/StaffDirectoryView.php
Labels: ready to test

#538 PCHR-4046: Fix security vulnerabilities
  package-lock.json
Labels: enhancement, ready to test

#540 Sync master with staging
  civicrm_resources/civicrm_resources.module
  civihr_employee_portal/civihr_employee_portal.install
  civihr_employee_portal/civihr_employee_portal.module
  civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.features.menu_links.inc
  civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.info
  civihr_employee_portal/src/View/StaffDirectoryView.php
  package-lock.json
Labels: release

#539 PCHR-4121: Fix SSP resources inclusion
  civicrm_resources/README.md
  civicrm_resources/README.txt
  civicrm_resources/civicrm_resources.module
  civihr_employee_portal/civihr_employee_portal.module
Labels: bug, enhancement, ready to test, regression

#542 PCHR-4139: Removing All Occurrencies of HRRecruitment
  civihr_employee_portal/civihr_employee_portal.module
Labels: ready to test
