Repository compucorp/civihr-employee-portal, pull requests merged in 2018-09, with the labels that each got.

#547 PCHR-4162: Remove taDocuments app
  civihr_employee_portal/civihr_employee_portal.module
  civihr_employee_portal/js/ta-documents-app.js
  civihr_employee_portal/views/templates/views-view-table--Documents--block.tpl.php
Labels: enhancement, ready to test

#548 PCHR-4034: Additional fixes
  civihr_employee_portal/src/Forms/OnboardingWizardCustomizationForm.php
Labels: enhancement

#537 PCHR-3681: Fixes for the CiviHR installation profile
  civihr_employee_portal/civihr_employee_portal.drush.inc
  civihr_employee_portal/civihr_employee_portal.info
  civihr_employee_portal/civihr_employee_portal.install
  civihr_employee_portal/civihr_employee_portal.module
  civihr_employee_portal/features/civihr_default_permissions/civihr_default_permissions.features.user_permission.inc
  civihr_employee_portal/features/civihr_default_permissions/civihr_default_permissions.info
  civihr_employee_portal/src/Helpers/NodeHelper.php
  civihr_employee_portal/views/views_export/views_hr_resource_types_list.inc
Labels: enhancement

#554 Sync master with staging
  civicrm_resources/README.md
  civicrm_resources/README.txt
  civicrm_resources/civicrm_resources.module
  civihr_employee_portal/civihr_employee_portal.install
  civihr_employee_portal/civihr_employee_portal.module
  civihr_employee_portal/features/civihr_default_permissions/civihr_default_permissions.features.user_permission.inc
  civihr_employee_portal/features/civihr_default_permissions/civihr_default_permissions.info
  civihr_employee_portal/js/ta-documents-app.js
  civihr_employee_portal/src/Forms/OnboardingWebForm.php
  civihr_employee_portal/src/Forms/OnboardingWizardCustomizationForm.php
  civihr_employee_portal/src/Helpers/WebformHelper.php
  civihr_employee_portal/src/Mail/AbstractDrupalSystemMail.php
  civihr_employee_portal/src/Mail/EmergencyContactDeletionNotificationMail.php
  civihr_employee_portal/src/Mail/MailContentReplacer.php
  civihr_employee_portal/src/Mail/OnboardingFormEditNotificationMail.php
  civihr_employee_portal/src/Mail/WebformSubmissionNotificationMail.php
  civihr_employee_portal/src/Service/ContactService.php
  civihr_employee_portal/src/Service/ContactUpdateNotificationSettingsHelper.php
  civihr_employee_portal/src/Service/EmergencyContactDeletionNotifier.php
  civihr_employee_portal/src/Service/WebformSubmissionNotifier.php
  civihr_employee_portal/src/View/CustomFieldsMappingFixer.php
  civihr_employee_portal/templates/smarty/dashboard_edit_details.tpl
  civihr_employee_portal/templates/smarty/emergency_contact_deletion.tpl
  civihr_employee_portal/views/templates/views-view-table--Documents--block.tpl.php
  civihr_employee_portal/views/views_export/views_mydetails_personal.inc
Labels: release

#532 PCHR-3930: Uninstall HR-Recruitment Extension
  civihr_employee_portal/civihr_employee_portal.install
  civihr_employee_portal/civihr_employee_portal.module
  civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.features.menu_links.inc
  civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.info
  civihr_employee_portal/views/civihr_employee_portal.views.inc
  civihr_employee_portal/views/views_export/views_hr_vacancies.inc
Labels: ready to test
