Repository compucorp/civihr-employee-portal, pull requests merged in 2018-02, with the labels that each got.

#438 PCHR-3259: Use lint staged for pre-commit linters
  .gitignore
  package-lock.json
  package.json
Labels: enhancement, ready to test

#440 PCHR-3285: Redirect from the SSP report pages to the CiviHR admin
  civihr_employee_portal/civihr_employee_portal.module
  civihr_employee_portal/templates/civihr-employee-portal-civihr-report-landing-page.tpl.php
Labels: enhancement

#441 PCHR-2592: Reporting UX improvements
  civihr_employee_portal/civihr_employee_portal.install
  civihr_employee_portal/civihr_employee_portal.module
  civihr_employee_portal/css/reports.css
  civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.features.menu_links.inc
  civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.info
  civihr_employee_portal/js/iframeResizer.contentWindow.min.js
  civihr_employee_portal/templates/civihr-employee-portal-civihr-report-landing-page.tpl.php
Labels: enhancement

#442 PCHR-3283: Remove the views_json_query dependency from the SSP
  civihr_employee_portal/civihr_employee_portal.info
  civihr_employee_portal/civihr_employee_portal.install
  civihr_employee_portal/views/civihr_employee_portal.views.inc
Labels: enhancement

#444 PCHR-3342: Style Users List
  civihr_employee_portal/civihr_employee_portal.module
  civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.views_default.inc
  civihr_employee_portal/templates/views-view-table-scrollable-with-results.tpl.php
  civihr_employee_portal/templates/views-view-table.tpl.php
  civihr_employee_portal/views/templates/views-view--users-list--page.tpl.php
  civihr_employee_portal/views/views_export/views_users_list.php
Labels: new feature
