Repository compucorp/civihr-employee-portal, pull requests merged in 2018-07, with the labels that each got.

#506 PCHR-3849: Google Analytics Implementation - Milestone 1
  civihr_employee_portal/civihr_employee_portal.module
Labels: ready to test

#509 PCHR-3793: Calendar feeds
  civihr_employee_portal/civihr_leave_absences/civihr_leave_absences.module
  civihr_employee_portal/features/civihr_default_permissions/civihr_default_permissions.features.user_permission.inc
  civihr_employee_portal/features/civihr_default_permissions/civihr_default_permissions.info
  civihr_employee_portal/src/Security/PublicFirewall.php
  civihr_employee_portal/tests/Security/PublicFirewallTest.php
Labels: new feature, ready to test

#513 PCHR-3950: Onbarding Wizard - Change Option Add Later to Skip this Step
  civihr_employee_portal/civihr_employee_portal.install
  civihr_employee_portal/features/node_export_files/onboarding_form.export
Labels: ready to test

#515 PCHR-3965: Job Roles Layout fixes
  civihr_employee_portal/views/views_export/views_mydetails_myrole.inc
Labels: bug

#517 PCHR-3969: Move City Above Postal Code in My Home Address Webform
  civihr_employee_portal/features/node_export_files/mydetails_home_address.export
Labels: bug

#518 PCHR-3970: Title for Contact Details not Displayed
  civihr_employee_portal/views/templates/views-view--my-details.tpl.php
Labels: bug

#516 PCHR-3964: Modifications for Personal Details Webform and Block
  civihr_employee_portal/features/node_export_files/mydetails_personal_details.export
  civihr_employee_portal/views/views_export/views_mydetails_personal.inc
Labels: bug

#521 Sync master with staging
  civihr_employee_portal/civihr_employee_portal.info
  civihr_employee_portal/civihr_employee_portal.install
  civihr_employee_portal/civihr_employee_portal.module
  civihr_employee_portal/civihr_leave_absences/civihr_leave_absences.module
  civihr_employee_portal/features/civihr_default_mail_content/civihr_default_mail_content.info
  civihr_employee_portal/features/civihr_default_mail_content/civihr_default_mail_content.strongarm.inc
  civihr_employee_portal/features/civihr_default_permissions/civihr_default_permissions.features.user_permission.inc
  civihr_employee_portal/features/civihr_default_permissions/civihr_default_permissions.features.user_role.inc
  civihr_employee_portal/features/civihr_default_permissions/civihr_default_permissions.info
  civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.features.field_instance.inc
  civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.features.filter.inc
  civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.features.taxonomy.inc
  civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.info
  civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.pages_default.inc
  civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.views_default.inc
  civihr_employee_portal/features/node_export_files/my_details.export
  civihr_employee_portal/features/node_export_files/mydetails_contact_details.export
  civihr_employee_portal/features/node_export_files/mydetails_home_address.export
  civihr_employee_portal/features/node_export_files/mydetails_payroll.export
  civihr_employee_portal/features/node_export_files/mydetails_personal_details.export
  civihr_employee_portal/features/node_export_files/onboarding_form.export
  civihr_employee_portal/src/Forms/OnboardingWizardCustomizationForm.php
  civihr_employee_portal/src/Helpers/TaxonomyHelper.php
  civihr_employee_portal/src/Security/PublicFirewall.php
  civihr_employee_portal/src/View/MyDetails_MyRoleView.php
  civihr_employee_portal/templates/civihr-employee-portal-my-details--block.tpl.php
  civihr_employee_portal/templates/smarty/user_account_activated.tpl
  civihr_employee_portal/templates/smarty/user_password_reset.tpl
  civihr_employee_portal/templates/views-exposed-form-users_list.tpl.php
  civihr_employee_portal/templates/views-exposed-form.tpl.php
  civihr_employee_portal/tests/Security/PublicFirewallTest.php
  civihr_employee_portal/views/civihr_employee_portal.views.inc
  civihr_employee_portal/views/includes/civihr_employee_portal_handler_aggregated_address.inc
  civihr_employee_portal/views/includes/civihr_employee_portal_handler_aggregated_personal_address.inc
  civihr_employee_portal/views/templates/_views-view--generic-display-output.tpl.php
  civihr_employee_portal/views/templates/views-view--default.tpl.php
  civihr_employee_portal/views/templates/views-view--manage-hr-resources-page.tpl.php
  civihr_employee_portal/views/templates/views-view--my-details.tpl.php
  civihr_employee_portal/views/templates/views-view--my-role.tpl.php
  civihr_employee_portal/views/templates/views-view-field--emergency-contacts--nothing.tpl.php
  civihr_employee_portal/views/templates/views-view-field--mydetails-personal--image-URL.tpl.php
  civihr_employee_portal/views/templates/views-view-field--mydetails-personal--ni-ssn-70.tpl.php
  civihr_employee_portal/views/templates/views-view-unformatted--mydetails-myrole.tpl.php
  civihr_employee_portal/views/views_export/views_emergency_contacts.inc
  civihr_employee_portal/views/views_export/views_hr_documents.inc
  civihr_employee_portal/views/views_export/views_my_details_block.inc
  civihr_employee_portal/views/views_export/views_mydetails_contactdetails.inc
  civihr_employee_portal/views/views_export/views_mydetails_emails.inc
  civihr_employee_portal/views/views_export/views_mydetails_myaddress.inc
  civihr_employee_portal/views/views_export/views_mydetails_myphones.inc
  civihr_employee_portal/views/views_export/views_mydetails_myrole.inc
  civihr_employee_portal/views/views_export/views_mydetails_payrollinformation.inc
  civihr_employee_portal/views/views_export/views_mydetails_personal.inc
  civihr_hrjobcontract_entities/civihr_hrjobcontract_entities.module
Labels: release

#522 PCHR-4010: Update path for reqangular.min.js
  civihr_employee_portal/civihr_employee_portal.module
Labels: bug, ready to test, regression

#524 PCHR-3999: Renames Permission to View System Status in Footer
  civihr_employee_portal/features/civihr_default_permissions/civihr_default_permissions.features.user_permission.inc
  civihr_employee_portal/features/civihr_default_permissions/civihr_default_permissions.info
Labels: ready to test

#525 Sync master with staging
  civihr_employee_portal/civihr_employee_portal.module
  civihr_employee_portal/features/civihr_default_permissions/civihr_default_permissions.features.user_permission.inc
  civihr_employee_portal/features/civihr_default_permissions/civihr_default_permissions.info
Labels: release

#527 PCHR-3941: Detach require.min.js from reqangular
  civihr_employee_portal/civihr_employee_portal.module
Labels: enhancement
