Repository compucorp/civihr-employee-portal, pull requests merged in 2018-06, with the labels that each got.

#475 Sync master with staging
  civihr_employee_portal/civihr_employee_portal.info
  civihr_employee_portal/civihr_employee_portal.module
  civihr_employee_portal/civihr_leave_absences/civihr_leave_absences.module
  civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.views_default.inc
  civihr_employee_portal/js/reports.js
  civihr_employee_portal/js/tasks.js
  civihr_employee_portal/templates/tasks_notification_badge.html
  civihr_employee_portal/views/civihr_employee_portal.views.inc
  civihr_employee_portal/views/includes/views_between_operation_dates_filter_handler.inc
  civihr_employee_portal/views/views_export/views_civihr_report_leave_and_absence.inc
Labels: release

#481 Sync master with staging
  civihr_employee_portal/js/reports.js
Labels: release

#478 PCHR-3706: Add default Resource Types
  civihr_employee_portal/civihr_employee_portal.install
  civihr_employee_portal/civihr_employee_portal.module
  civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.features.taxonomy.inc
  civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.info
  civihr_employee_portal/src/Helpers/TaxonomyHelper.php
Labels: new feature

#491 PCHR-3837: onboarding wizard improvements
  civihr_employee_portal/civihr_employee_portal.install
  civihr_employee_portal/civihr_employee_portal.module
  civihr_employee_portal/features/node_export_files/onboarding_form.export
  civihr_employee_portal/src/Forms/OnboardingWizardCustomizationForm.php
Labels: ready to test

#497 PCHR-3861: Fill data layer container on module init
  civihr_employee_portal/civihr_employee_portal.module
Labels: new feature, ready to test

#486 PCHR-3674: HR Resources Screen Changes
  civihr_employee_portal/civihr_employee_portal.install
  civihr_employee_portal/civihr_employee_portal.module
  civihr_employee_portal/features/civihr_default_permissions/civihr_default_permissions.features.user_permission.inc
  civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.features.field_instance.inc
  civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.features.taxonomy.inc
  civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.info
  civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.views_default.inc
  civihr_employee_portal/src/Helpers/TaxonomyHelper.php
  civihr_employee_portal/views/templates/views-view--manage-hr-resources-page.tpl.php
Labels: enhancement, new feature

#500 PCHR-3835: Fix url for title in Manage HR Resources Page
  civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.views_default.inc
Labels: bug
