Repository compucorp/civihr-employee-portal, pull requests merged in 2018-05, with the labels that each got.

#465 Sync master with staging
  civihr_employee_portal/civihr_employee_portal.install
  civihr_employee_portal/civihr_employee_portal.module
  civihr_employee_portal/features/civihr_default_permissions/civihr_default_permissions.features.user_permission.inc
  civihr_employee_portal/features/civihr_default_permissions/civihr_default_permissions.info
  civihr_employee_portal/features/node_export_files/onboarding_form.export
  civihr_employee_portal/src/Webform/CustomComponentKeyHelper.php
  civihr_employee_portal/src/Webform/WebformExportCustomFieldConvertor.php
  civihr_employee_portal/templates/civihr-employee-portal-user-login.tpl.php
  civihr_employee_portal/tests/Webform/CustomComponentKeyHelperTest.php
  civihr_employee_portal/tests/Webform/WebformExportCustomFieldConvertorTest.php
  civihr_employee_portal/views/civihr_employee_portal.views.inc
  civihr_employee_portal/views/views_export/views_hr_staff_directory.inc
Labels: release

#471 PCHR-3673: Count of Assigned Task and Documents
  civihr_employee_portal/civihr_employee_portal.module
  civihr_employee_portal/civihr_leave_absences/civihr_leave_absences.module
  civihr_employee_portal/js/tasks.js
  civihr_employee_portal/templates/tasks_notification_badge.html
Labels: new feature, ready to test

#472 PCHR-3703: New page for Managing HR Resources
  civihr_employee_portal/civihr_employee_portal.module
  civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.info
  civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.views_default.inc
  civihr_employee_portal/views/templates/views-view--manage-hr-resources-page.tpl.php
Labels: new feature
